/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package priyanka_marandi;

/**
 *
 * @author Priyanka Marandi
 */
public class calculator extends javax.swing.JFrame {

    /**
     * Creates new form calculator
     */
    
    double NumEnter1;
    double NumEnter2;
    double result;
    String op;
    public calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        btnpm = new javax.swing.JButton();
        btnbs = new javax.swing.JButton();
        btnce = new javax.swing.JButton();
        btnC = new javax.swing.JButton();
        btnsymP = new javax.swing.JButton();
        btndigit7 = new javax.swing.JButton();
        btndigit8 = new javax.swing.JButton();
        btndigit9 = new javax.swing.JButton();
        btnsymM = new javax.swing.JButton();
        btndigit4 = new javax.swing.JButton();
        btndigit5 = new javax.swing.JButton();
        btndigit6 = new javax.swing.JButton();
        btnsymMul = new javax.swing.JButton();
        btndigit1 = new javax.swing.JButton();
        btndigit2 = new javax.swing.JButton();
        btndigit3 = new javax.swing.JButton();
        btnsymequals = new javax.swing.JButton();
        btnsymdiv = new javax.swing.JButton();
        btndigit0 = new javax.swing.JButton();
        btnsymdec = new javax.swing.JButton();
        jtxtresults = new javax.swing.JTextField();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnpm.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnpm.setText("±");
        btnpm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpmActionPerformed(evt);
            }
        });
        getContentPane().add(btnpm, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 80, 70));

        btnbs.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnbs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/priyanka_marandi/icons8-back-button-50.png"))); // NOI18N
        btnbs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbsActionPerformed(evt);
            }
        });
        getContentPane().add(btnbs, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 80, 70));

        btnce.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnce.setText("CE");
        btnce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnceActionPerformed(evt);
            }
        });
        getContentPane().add(btnce, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 80, 70));

        btnC.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnC.setText("C");
        getContentPane().add(btnC, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 80, 70));

        btnsymP.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnsymP.setText("+");
        btnsymP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsymPActionPerformed(evt);
            }
        });
        getContentPane().add(btnsymP, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 80, 70));

        btndigit7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btndigit7.setText("7");
        btndigit7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndigit7ActionPerformed(evt);
            }
        });
        getContentPane().add(btndigit7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 80, 70));

        btndigit8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btndigit8.setText("8");
        btndigit8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndigit8ActionPerformed(evt);
            }
        });
        getContentPane().add(btndigit8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 80, 70));

        btndigit9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btndigit9.setText("9");
        btndigit9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndigit9ActionPerformed(evt);
            }
        });
        getContentPane().add(btndigit9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 80, 70));

        btnsymM.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnsymM.setText("-");
        btnsymM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsymMActionPerformed(evt);
            }
        });
        getContentPane().add(btnsymM, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 80, 70));

        btndigit4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btndigit4.setText("4");
        btndigit4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndigit4ActionPerformed(evt);
            }
        });
        getContentPane().add(btndigit4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 80, 70));

        btndigit5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btndigit5.setText("5");
        btndigit5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndigit5ActionPerformed(evt);
            }
        });
        getContentPane().add(btndigit5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 80, 70));

        btndigit6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btndigit6.setText("6");
        btndigit6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndigit6ActionPerformed(evt);
            }
        });
        getContentPane().add(btndigit6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 80, 70));

        btnsymMul.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnsymMul.setText("*");
        btnsymMul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsymMulActionPerformed(evt);
            }
        });
        getContentPane().add(btnsymMul, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 80, 70));

        btndigit1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btndigit1.setText("1");
        btndigit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndigit1ActionPerformed(evt);
            }
        });
        getContentPane().add(btndigit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 80, 70));

        btndigit2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btndigit2.setText("2");
        btndigit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndigit2ActionPerformed(evt);
            }
        });
        getContentPane().add(btndigit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 80, 70));

        btndigit3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btndigit3.setText("3");
        btndigit3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndigit3ActionPerformed(evt);
            }
        });
        getContentPane().add(btndigit3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 80, 70));

        btnsymequals.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnsymequals.setText("=");
        btnsymequals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsymequalsActionPerformed(evt);
            }
        });
        getContentPane().add(btnsymequals, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, 80, 70));

        btnsymdiv.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnsymdiv.setText("/");
        btnsymdiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsymdivActionPerformed(evt);
            }
        });
        getContentPane().add(btnsymdiv, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 80, 70));

        btndigit0.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btndigit0.setText("0");
        btndigit0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndigit0ActionPerformed(evt);
            }
        });
        getContentPane().add(btndigit0, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, 80, 70));

        btnsymdec.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnsymdec.setText(".");
        btnsymdec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsymdecActionPerformed(evt);
            }
        });
        getContentPane().add(btnsymdec, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, 80, 70));

        jtxtresults.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtresults.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(jtxtresults, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 350, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void EnterNumber(String q)
{
    String nums=jtxtresults.getText() + q;
    jtxtresults.setText(nums);
}
    private void btndigit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndigit2ActionPerformed
        EnterNumber("2");
    }//GEN-LAST:event_btndigit2ActionPerformed

    private void btndigit0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndigit0ActionPerformed
        EnterNumber("0");
    }//GEN-LAST:event_btndigit0ActionPerformed

    private void btndigit7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndigit7ActionPerformed
        // TODO add your handling code here:
        EnterNumber("7");
    }//GEN-LAST:event_btndigit7ActionPerformed

    private void btndigit8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndigit8ActionPerformed
        EnterNumber("8");
    }//GEN-LAST:event_btndigit8ActionPerformed

    private void btndigit9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndigit9ActionPerformed
        EnterNumber("9");
    }//GEN-LAST:event_btndigit9ActionPerformed

    private void btndigit4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndigit4ActionPerformed
        EnterNumber("4");
    }//GEN-LAST:event_btndigit4ActionPerformed

    private void btndigit5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndigit5ActionPerformed
        EnterNumber("5");
    }//GEN-LAST:event_btndigit5ActionPerformed

    private void btndigit6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndigit6ActionPerformed
        EnterNumber("6");
    }//GEN-LAST:event_btndigit6ActionPerformed

    private void btndigit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndigit1ActionPerformed
        EnterNumber("1");
    }//GEN-LAST:event_btndigit1ActionPerformed

    private void btndigit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndigit3ActionPerformed
        EnterNumber("3");
    }//GEN-LAST:event_btndigit3ActionPerformed

    private void btnsymdivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsymdivActionPerformed
        NumEnter1=Double.parseDouble(jtxtresults.getText());
        jtxtresults.setText("");
        op="/";
    }//GEN-LAST:event_btnsymdivActionPerformed

    private void btnsymMulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsymMulActionPerformed
        NumEnter1=Double.parseDouble(jtxtresults.getText());
        jtxtresults.setText("");
        op="*";
    }//GEN-LAST:event_btnsymMulActionPerformed

    private void btnsymMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsymMActionPerformed
        NumEnter1=Double.parseDouble(jtxtresults.getText());
        jtxtresults.setText("");
        op="-";
    }//GEN-LAST:event_btnsymMActionPerformed

    private void btnsymPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsymPActionPerformed
        NumEnter1=Double.parseDouble(jtxtresults.getText());
        jtxtresults.setText("");
        op="+";
    }//GEN-LAST:event_btnsymPActionPerformed

    private void btnceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnceActionPerformed
        jtxtresults.setText("");
        
        String fn, sn;
        fn=String.valueOf(NumEnter1);
        sn=String.valueOf(NumEnter2);
        
        fn="";
        sn="";
    }//GEN-LAST:event_btnceActionPerformed

    private void btnpmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpmActionPerformed
       double  nums=Double.parseDouble(String.valueOf(jtxtresults.getText()));
       nums=nums * (-1);
       jtxtresults.setText(String.valueOf(nums));
    }//GEN-LAST:event_btnpmActionPerformed

    private void btnbsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbsActionPerformed
        String backs=null;
        if(jtxtresults.getText().length()>0)
        {
            StringBuilder sb=new StringBuilder(jtxtresults.getText());
            sb.deleteCharAt(jtxtresults.getText().length()-1);
            backs=sb.toString();
            jtxtresults.setText(backs);
        }
    }//GEN-LAST:event_btnbsActionPerformed

    private void btnsymdecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsymdecActionPerformed
        if(! jtxtresults.getText().contains("."))
        {
            jtxtresults.setText(jtxtresults.getText() +btnsymdec.getText());
        }
    }//GEN-LAST:event_btnsymdecActionPerformed

    private void btnsymequalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsymequalsActionPerformed
        NumEnter2=Double.parseDouble(jtxtresults.getText());
        if(op == "+")
        {
            result=NumEnter1 +NumEnter2;
            jtxtresults.setText(String.valueOf(result));
        }
        
        else if(op == "-")
        {
            result=NumEnter1 - NumEnter2;
            jtxtresults.setText(String.valueOf(result));
        }
        
        else if(op == "*")
        {
            result=NumEnter1 * NumEnter2;
            jtxtresults.setText(String.valueOf(result));
        }
        else if(op == "/")
        {
            result=NumEnter1 / NumEnter2;
            jtxtresults.setText(String.valueOf(result));
        }
    }//GEN-LAST:event_btnsymequalsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnC;
    private javax.swing.JButton btnbs;
    private javax.swing.JButton btnce;
    private javax.swing.JButton btndigit0;
    private javax.swing.JButton btndigit1;
    private javax.swing.JButton btndigit2;
    private javax.swing.JButton btndigit3;
    private javax.swing.JButton btndigit4;
    private javax.swing.JButton btndigit5;
    private javax.swing.JButton btndigit6;
    private javax.swing.JButton btndigit7;
    private javax.swing.JButton btndigit8;
    private javax.swing.JButton btndigit9;
    private javax.swing.JButton btnpm;
    private javax.swing.JButton btnsymM;
    private javax.swing.JButton btnsymMul;
    private javax.swing.JButton btnsymP;
    private javax.swing.JButton btnsymdec;
    private javax.swing.JButton btnsymdiv;
    private javax.swing.JButton btnsymequals;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jtxtresults;
    // End of variables declaration//GEN-END:variables
}
